### ISSUE TITLE
Live editing breaks with Astro Dynamic Tags

### ISSUE THREAD

**Issue by silveltman** [CloudCannon/bookshop#187] opened 2024-01-24 13:42 UTC
This breaks live editing:
```astro
---
export interface Props {
  heading?: string | null
  level?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  class?: string
}

const { level = 'h2', heading, class: className } = Astro.props
const Level = level

const slot = await Astro.slots.render('default')
---

{
  (heading || slot?.trim().length > 0) && (
    <Level class:list={['heading', className]}>
      {heading}
      <slot />
    </Level>
  )
}
```

and this does not:
```astro
---
export interface Props {
  heading?: string | null
  level?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'
  class?: string
}

const { level = 'h2', heading, class: className } = Astro.props
const Level = level

const slot = await Astro.slots.render('default')
---

{
  (heading || slot?.trim().length > 0) && (
    <h1 class:list={['heading', className]}>
      {heading}
      <slot />
    </Level>
  )
}

**Comment by oliverlynch** [comment] 2024-03-27 05:29
I have also run into this issue; when rendering a similar component in the component browser this exception occurs:

```
Uncaught (in promise) TypeError: Component is not a function
    renderToStaticMarkup bookshop.js:40883
    renderFrameworkComponent bookshop.js:43125
    renderComponent2 bookshop.js:43300
    Heading bookshop.js:44226
    Heading bookshop.js:44238
    fn bookshop.js:41783
    callComponentAsTemplateResultOrResponse bookshop.js:40805
    renderToString bookshop.js:40782
    renderAstroComponent bookshop.js:40982
    render bookshop.js:40933
```

The `Component` variable passed to `renderToStaticMarkup` is the tag to render as a string ("h1", "h2", ect.), but it calls it as if it is a function. 

```
const reactNode = await Component(props);
```

Not ideal, but in the meantime this accomplishes the same thing:
```
{Element === "h1" && <h1>{heading}</h1>}
{Element === "h2" && <h2>{heading}</h2>}
{Element === "h3" && <h3>{heading}</h3>}
```

**Comment by edmeehan** [comment] 2024-03-30 21:17
I can confirm I am having the same issue. It was not an issue a few months ago, but I'm not sure if my local codebase or Bookshop changed to cause this issue.

**Comment by edmeehan** [comment] 2024-04-16 18:00
Any word on this? Is this an Astro or Bookshop issue? I didn't change my local Astro version and even tried to roll back to the CloudCannon legacy editor.

**Comment by edmeehan** [comment] 2024-04-17 18:27
I have tried changing the version of Astro and other various packages, and there has been no change. Considering that this happened when no changes were made, this has something to do with an update to CC live preview editor.

This is the error as I see it in console:
```
Error rendering bookshop component page TypeError: Component is not a function
renderElement @ bookshop-live.js:33590
```

This is the function as it is shown in console:
```
async renderElement(componentName, scope, dom, logger) {
      try {
        logger?.log?.(`Rendering ${componentName}`);
        await this.engines[0].render(dom, componentName, scope, { ...this.globalData }, logger?.nested?.());
        logger?.log?.(`Rendered ${componentName}`);
      } catch (e) {
        logger?.log?.(`Error rendering ${componentName}`);
        console.warn(`Error rendering bookshop component ${componentName}`, e.toString());
        console.warn(`This is expected in certain cases, and may not be an issue, especially when deleting or re-ordering components.`);
      }
    }
```

Component is the name of the dynamic tag I am using. I followed the pattern used in [sendit-astro](https://github.com/CloudCannon/sendit-astro-template/blob/main/src/shared/astro/page.jsx), which has worked fine for months but only recently started throwing this error.

This is a roadblock for me to use Astro & CC as a CMS, I have a client site running on CC & 11ty, and hoped to start building in Astro with new projects.

**Comment by Tate-CC** [comment] 2024-04-18 04:41
Hi @edmeehan, sorry but we haven't been able to prioritise looking into this issue yet!

But it certainly is suspicious that you've started encountering errors without changing anything on your end. If you could share some more information about your setup or provide a minimal reproduction that'd be really helpful in debugging!

I wouldn't have expected you to hit this issue just following the Sendit template, since that only uses dynamic tags to render other components, which would ultimately be built to actual functions. This should only happen if you have dynamic tags which are string literals, so it'd be good to have a look and make sure that there isn't anything else secretly behind your problem.

**Comment by edmeehan** [comment] 2024-04-25 18:32
As @silveltman and @oliverlynch have noted, the work around is conditional display of the tag, and Astro dynamic tags appear to be broken in the live preview. I was able to solve my issue, but luckily my dynamic tag currently only had two options.

**Comment by Tate-CC** [comment] 2024-05-21 22:02
Hi all 🙋 (@edmeehan @silveltman @oliverlynch) Just a heads up that this has been fixed in the latest release of Bookshop (3.10.0)! Thanks for you patience while we worked on this!

Bookshop 3.10.0 includes a number of smaller fixes that we don't have issues for, but were common pain points for Astro, so you might want to check out the changelog and see if there's anything else in there that applies to you

**Closed by Tate-CC** 2024-05-21 22:02 UTC

**Comment by silveltman** [comment] 2024-05-22 15:14
Great @Tate-CC !

Are there also fixes that prevent the live editor breaking when using destructred props? I reported quiet a lot of bugs like that via chat some time ago. They just kept coming so I gave up then.

If these sound familiar and are fixed I think I can give it another try!

**Comment by Tate-CC** [comment] 2024-05-28 00:45
Hi @silveltman!

I don't believe there were any fixes to destructured props included specifically in the release.

If I recall it was to do with destructuring the root frontmatter object, does that sound right? If you happen to still have a reproduction case around, you could put that into it's own issue thread and I could investigate whether or not it's something we can fix as a fast follow!
